### PR TITLE
Update package structure how & why docs

### LINKED ISSUE #20: Replace retrying pkg with tenancity in pkg structure docs
`retrying` package appears to be no longer maintained. `tenacity` is an activate fork with improvements and some API differences.

### PR DESCRIPTION
**Pull request by douglatornell**
Big update that arises from Doug's review of the Python packaging landscape in Nov-2022 to Jan-2023.
That review resulted in changing to use `hatchling` for the build backend, and finally being able to move all packaing configuration and metadata to `pyproject.toml` (i.e. goodby `setup.py` and `setup.cfg`).

Rendering of the updated version of the docs produced from this PR is at https://ubc-moad-docs.readthedocs.io/en/update-pkg-structure/python_packaging/pkg_structure.html

### CODE REVIEW

**Comment by douglatornell** [comment]
@SusanEAllen I would appreciate you reviewing this because I've been looking at it and thinking about it for so long that I'm sure that there are things that I can't see. I realize that it is pretty deep in Python packaging lore, but my hope is that it is still somewhat understandable.

The link to the rendering of the section from this branch is above. I think that you should be able to leave comments in the diff view of this PR if you want. You should also be able to choose the branch in the GitHub interface and edit the file in the web editor if you want, then commit your changes to the PR.

**Comment by douglatornell** [comment]
@SusanEAllen Nudge :smile_cat:

**Comment by douglatornell** [comment]
@SusanEAllen Nudge :smile_cat:

**Comment by SusanEAllen** [comment]
The six-files section and the Package Files section are almost identical and very repetitive.  Suggest you move the package files section (nicer layout) up to the six files, or reference the Package Files section in the six files section.

**Review by SusanEAllen — APPROVED** [review]
Good given previous comments.

**Pull request merged**
